---
- name: Install and configure Vim
  block:

    - name: Full version of vim installed
      ansible.builtin.apt:
        pkg:
          - vim
        state: present
        update_cache: false

    - name: Vim set as default editor
      community.general.alternatives:
        name: editor
        path: /usr/bin/vim.basic
      when: vim_alternatives

    - name: Getent passwd
      ansible.builtin.getent:
        database: passwd
        key: "{{ vim_user }}"
        split: ':'

    - name: Debug getent passwd
      ansible.builtin.debug:
        var: getent_passwd
        verbosity: 2

    - name: Set a fact for the users HOME
      ansible.builtin.set_fact:
        vim_home: "{{ user.value[4] }}"
      when: user.key == vim_user
      loop: "{{ getent_passwd | dict2items }}"
      loop_control:
        extended: true
        loop_var: user
        label: "{{ user.key }}"

    - name: ~/.vimrc in place
      ansible.builtin.template:
        src: vimrc.j2
        dest: "{{ vim_home }}/.vimrc"
        force: false
        mode: 0640
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"

    - name: ~/.vim directories present
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
        recurse: true
        mode: 0750
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"
      loop:
        - /root/.vim
        - /root/.vim/syntax
        - /root/.vim/plugin
      loop_control:
        loop_var: dir
        label: "{{ dir }}"

    - name: Securemodelines plugin in place
      ansible.builtin.template:
        src: securemodelines.vim.j2
        dest: "{{ vim_home }}/.vim/plugin/securemodelines.vim"
        mode: 0640
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"

    - name: Nginx syntax highlighting in place
      ansible.builtin.template:
        src: nginx.vim.j2
        dest: /root/.vim/syntax/nginx.vim
        mode: 0640
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"

    - name: Add Nginx to filetype.vim
      ansible.builtin.lineinfile:
        path: "{{ vim_home }}/.vim/filetype.vim"
        line: "au BufRead,BufNewFile /etc/nginx/*,/etc/nginx/conf.d/*,/etc/nginx/sites-available/*,/etc/nginx/sites-enabled/* if &ft == '' | setfiletype nginx | endif"
        state: present
        create: true
        mode: 0640
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"

    - name: ~/.selected_editor in place
      ansible.builtin.template:
        src: selected_editor.j2
        dest: "{{ vim_home }}/.selected_editor"
        mode: 0640
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"
      when: vim_selected

  when: vim
  tags:
    - vim
...
