# Copyright 2022-2024 Chris Croome
#
# This file is part of the Webarchitects Vim Ansible role.
#
# The Webarchitects Vim Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Vim Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Vim Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Install and configure Vim
  block:

    - name: Full version of vim installed
      ansible.builtin.apt:
        pkg:
          - vim
          - vim-icinga2
        state: present
        update_cache: false
      when: ansible_facts.effective_user_id == 0

    - name: Vim set as default editor
      community.general.alternatives:
        name: editor
        path: "{{ vim_path }}"
      when: vim_alternatives

    - name: Getent passwd
      ansible.builtin.getent:
        database: passwd
        key: "{{ vim_user }}"
        split: ':'

    - name: Debug getent passwd
      ansible.builtin.debug:
        var: getent_passwd
        verbosity: 2

    - name: Set a fact for the users HOME
      ansible.builtin.set_fact:
        vim_home: "{{ user.value[4] }}"
      when: user.key == vim_user
      loop: "{{ getent_passwd | dict2items }}"
      loop_control:
        extended: true
        loop_var: user
        label: "{{ user.key }}"

    - name: Stat ~/.vimrc
      ansible.builtin.stat:
        path: "{{ vim_home }}/.vimrc"
      register: vim_vimrc

    - name: ~/.vimrc in place if it doesn't exist or is empty
      ansible.builtin.template:
        src: vimrc.j2
        dest: "{{ vim_home }}/.vimrc"
        force: "{% if not vim_vimrc.stat.exists or vim_vimrc.stat.blocks == 0 %}true{% else %}false{% endif %}"
        mode: "0640"
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"

    - name: ~/.vim directories present
      ansible.builtin.file:
        path: "{{ vim_home }}{{ dir }}"
        state: directory
        mode: "0750"
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"
      loop:
        - /.vim
        - /.vim/syntax
        - /.vim/plugin
      loop_control:
        loop_var: dir
        label: "{{ dir }}"

    - name: Securemodelines plugin in place
      ansible.builtin.template:
        src: securemodelines.vim.j2
        dest: "{{ vim_home }}/.vim/plugin/securemodelines.vim"
        mode: "0640"
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"

    - name: Nginx syntax highlighting in place
      ansible.builtin.template:
        src: nginx.vim.j2
        dest: /root/.vim/syntax/nginx.vim
        mode: "0640"
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"

    - name: Add Nginx to filetype.vim
      ansible.builtin.lineinfile:
        path: "{{ vim_home }}/.vim/filetype.vim"
        line: "au BufRead,BufNewFile /etc/nginx/*,/etc/nginx/conf.d/*,/etc/nginx/sites-available/*,/etc/nginx/sites-enabled/* if &ft == '' | setfiletype nginx | endif"
        state: present
        create: true
        mode: "0640"
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"

    - name: ~/.selected_editor in place
      ansible.builtin.template:
        src: selected_editor.j2
        dest: "{{ vim_home }}/.selected_editor"
        mode: "0640"
        owner: "{{ vim_user }}"
        group: "{{ vim_group }}"
      when: vim_selected

  when: vim
  tags:
    - vim
...
